//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gsb.rc
//
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_COMP                        106
#define IDC_GSB                         109
#define IDC_OKPING                      109
#define IDR_MAINFRAME                   128
#define IDI_Q2                          132
#define IDI_ICON1                       134
#define IDI_ICON2                       135
#define IDI_SERVER                      135
#define IDI_ICON3                       136
#define IDI_ICON4                       137
#define IDI_ICON5                       138
#define IDI_ICON6                       139
#define IDC_STATUSBAR                   140
#define IDD_ADDSERVER                   162
#define IDD_DIALOG1                     164
#define IDD_GSB_PROXY                   164
#define IDD_DIALOG2                     165
#define IDD_MAIN                        165
#define IDI_WIN32                       168
#define IDI_LINUX                       169
#define IDI_FREEBSD                     170
#define IDI_MACOSX                      171
#define	IDB_BITMAP0						236
#define IDB_BITMAP1                     237
#define IDB_BITMAP2                     238
#define IDB_BITMAP3                     239
#define IDB_BITMAP4                     240
#define IDB_BITMAP5                     241
#define IDB_BITMAP6                     242
#define IDB_BITMAP7                     243
#define IDB_BITMAP8                     244
#define IDB_BITMAP9                     245
#define IDB_BITMAP10                    246
#define IDB_BITMAP11                    247
#define IDB_BITMAP12                    248
#define IDB_BITMAP13                    249
#define IDB_BITMAP14                    250
#define IDB_BITMAP15                    251
#define IDB_BITMAP16                    252
#define IDB_BITMAP17                    253
#define IDB_BITMAP18                    254
#define IDB_BITMAP19                    255
#define IDB_BITMAP20                    256
#define IDB_BITMAP21                    257
#define IDB_BITMAP22                    258
#define IDB_BITMAP23                    259
#define IDB_BITMAP24                    260
#define IDB_BITMAP25                    261
#define IDB_BITMAP26                    262
#define IDB_BITMAP27                    263
#define IDB_BITMAP28                    264
#define IDB_BITMAP29                    265
#define IDB_BITMAP30                    266
#define IDB_BITMAP31                    267
#define IDB_BITMAP32                    268
#define IDB_BITMAP33                    269
#define IDB_BITMAP34                    270
#define IDB_BITMAP35                    271
#define IDB_BITMAP36                    272
#define IDB_BITMAP37                    273
#define IDB_BITMAP38                    274
#define IDB_BITMAP39                    275
#define IDB_BITMAP40                    276
#define IDB_BITMAP41                    277
#define IDB_BITMAP42                    278
#define IDB_BITMAP43                    279
#define IDB_BITMAP44                    280
#define IDB_BITMAP45                    281
#define IDB_BITMAP46                    282
#define IDB_BITMAP47                    283
#define IDB_BITMAP48                    284
#define IDB_BITMAP49                    285
#define IDB_BITMAP50                    286
#define IDB_BITMAP51                    287
#define IDB_BITMAP52                    288
#define IDB_BITMAP53                    289
#define IDB_BITMAP54                    290
#define IDB_BITMAP55                    291
#define IDB_BITMAP56                    292
#define IDB_BITMAP57                    293
#define IDB_BITMAP58                    294
#define IDB_BITMAP59                    295
#define IDB_BITMAP60                    296
#define IDB_BITMAP61                    297
#define IDB_BITMAP62                    298
#define IDB_BITMAP63                    299
#define IDB_BITMAP64                    300
#define IDC_PROGRESS1                   1001
#define IDC_PRETTY                      1002
#define IDC_CANCEL                      1003
#define IDC_STATUSMSG                   1004
#define IDC_ALT                         1013
#define IDC_Q2PATH                      1014
#define IDC_Q2EXE                       1015
#define IDC_SERVERLIST                  1017
#define IDC_PLAYERS                     1018
#define IDC_EXIT                        1019
#define IDC_CONFIG                      1020
#define IDC_UPDATE                      1021
#define IDC_SERVERFRAME                 1022
#define IDC_PLAYERSFRAME                1023
#define IDC_CONTROLSFRAME               1024
#define IDC_BUDDIES                     1025
#define IDC_PPS                         1027
#define IDC_GOODPING                    1028
#define IDC_INCLUDE_FULL                1028
#define IDC_INCLUDE_EMPTY               1029
#define IDC_MOD                         1031
#define IDC_GAMETYPE                    1032
#define IDC_FILTERGROUP                 1034
#define IDC_LABELMOD                    1035
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        300
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
